name: Publish docker image

on:
  push:
    paths:
    - 'uwsgi-base/*'

jobs:

    build:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            echo ::set-output name=tag::,${GITHUB_REF:10}
          else
            echo ::set-output name=tag::
          fi

      - name: Publish alpine docker image to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: sourcepole/qwc-uwsgi-base
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "latest,alpine-latest${{ steps.get_tag.outputs.tag }}"
          dockerfile: uwsgi-base/alpine/Dockerfile

      - name: Publish ubuntu docker image to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: sourcepole/qwc-uwsgi-base
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "ubuntu-latest${{ steps.get_tag.outputs.tag }}"
          dockerfile: uwsgi-base/ubuntu/Dockerfile
